#include <stdio.h>
#include <stdlib.h>


int main()
{
        system("COLOR B");
        printf("-------------------------------------------------------------------\n");
        printf("|                         Input your resume                       |\n");
        printf("-------------------------------------------------------------------\n");

        printf("                  \n");
        printf("-------------------------------------------------------------------\n");
    char name [150] ;
        printf("First Name =");
        scanf("%s",& name);
        printf(" First Name = %s\n",name);
        printf("-------------------------------------------------------------------\n");
    char last [150] ;
        printf("Last Name =");
        scanf("%s",& last);
        printf(" Last Name = %s\n",last);
        printf("-------------------------------------------------------------------\n");
    char position [150] ;
        printf("Position Applied for =");
        scanf("%s",& position);
        printf(" Position Applied for = %s\n",position);
        printf("-------------------------------------------------------------------\n");
    char salary [150] ;
        printf("Salary =");
        scanf("%s",& salary);
        printf(" Salary = %s\n",salary);
        printf("-------------------------------------------------------------------\n");
    char address [150] ;
        printf("Present address =");
        scanf("%s",& address);
        printf(" Present address = %s\n",address);
        printf("-------------------------------------------------------------------\n");
    char moo [150] ;
        printf("Moo =");
        scanf("%s",& moo);
        printf(" Moo = %s\n",moo);
        printf("-------------------------------------------------------------------\n");
    char road [150] ;
        printf("Road =");
        scanf("%s",& road);
        printf(" Road = %s\n",road);
        printf("-------------------------------------------------------------------\n");
    char district [150] ;
        printf("District =");
        scanf("%s",& district);
        printf(" Road = %s\n",road);
        printf("-------------------------------------------------------------------\n");
    char amphur [150] ;
        printf("Amphur =");
        scanf("%s",& amphur);
        printf(" Amphur = %s\n",amphur);
        printf("-------------------------------------------------------------------\n");
    char province [150] ;
        printf("Province =");
        scanf("%s",& province);
        printf(" Province = %s\n",province);
        printf("-------------------------------------------------------------------\n");
    char post [150] ;
        printf("Post code =");
        scanf("%s",& post);
        printf(" Post code = %s\n",post);
        printf("-------------------------------------------------------------------\n");
    char tel [150] ;
        printf("Tel. =");
        scanf("%s",& tel);
        printf(" Tel. = %s\n",tel);
        printf("-------------------------------------------------------------------\n");
    char pager [150] ;
        printf("Pager =");
        scanf("%s",& pager);
        printf(" Pager = %s\n",pager);
        printf("-------------------------------------------------------------------\n");
    char mobile [150] ;
        printf("Mobile =");
        scanf("%s",& mobile);
        printf(" Mobile = %s\n",mobile);
        printf("-------------------------------------------------------------------\n");
    char email [150] ;
        printf("E-mail =");
        scanf("%s",& email);
        printf(" E-mail = %s\n",email);
        printf("-------------------------------------------------------------------\n");
        printf("                  \n");
        system("COLOR A");
        printf("-------------------------------------------------------------------\n");
        printf("|                            Your resume                          |\n");
        printf("-------------------------------------------------------------------\n");
        printf("                  \n");
        printf(" First Name = %s\n",name);
        printf(" Last Name = %s\n",last);
        printf(" Position Applied for = %s\n",position);
        printf(" Salary = %s\n",salary);
        printf(" Present address = %s\n",address);
        printf(" Moo = %s\n",moo);
        printf(" Road = %s\n",road);
        printf(" Amphur = %s\n",amphur);
        printf(" Province = %s\n",province);
        printf(" Post code = %s\n",post);
        printf(" Tel. = %s\n",tel);
        printf(" Pager = %s\n",pager);
        printf(" Mobile = %s\n",mobile);
        printf(" E-mail = %s\n",email);
        printf("                  \n");
        printf("-------------------------------------------------------------------\n");
        printf("                  \n");
        return 0;
}
